[package]
name = "realize"
version = "0.1.0"
authors = ["ashtneoi <ashtneoi@gmail.com>"]
edition = "2018"

[dependencies]
ron = "0.5.1"
serde = { version = "1.0.90", features = ["derive"] }
sha2 = "0.8.0"
